# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Hyperdrive < Formula
  desc "Accelerate from zero to a lando-based dev environment in less then 12 par-steps"
  homepage "https://github.com/lando/hyperdrive"
  url "https://github.com/lando/hyperdrive/archive/v0.7.0-alpha.17.tar.gz"
  sha256 "b44f2eb83d43ea164ad7344ba4837378ce573f6ed4a0a07cd90a13a85900d3ee"
  license "GPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/lando/hyperdrive/releases/download/v0.7.0-alpha.17/hyperdrive-macos-x64-v0.7.0-alpha.17.tar.gz"
      sha256 "960ee8f9bd7db8441e2d9b81d29ecd4217c0ed4805a252e1d21194cce1bef979"
    end

    on_arm do
      url "https://github.com/lando/hyperdrive/releases/download/v0.7.0-alpha.17/hyperdrive-macos-arm64-v0.7.0-alpha.17.tar.gz"
      sha256 "ba7aee24d63ebb40ef0eb4b8559b0937fac2438c19111367c623a0b1e4ce83f1"
    end
  end

  def install
    bin.install "hyperdrive-macos-#{arch}-v#{version}" => "hyperdrive"
  end

  test do
    system "#{bin}/hyperdrive" "--version"
  end
end
