# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Hyperdrive < Formula
  desc "Accelerate from zero to a lando-based dev environment in less then 12 par-steps"
  homepage "https://github.com/lando/hyperdrive"
  url "https://github.com/lando/hyperdrive/archive/v0.7.0-alpha.17.tar.gz"
  sha256 "b44f2eb83d43ea164ad7344ba4837378ce573f6ed4a0a07cd90a13a85900d3ee"
  license "GPL-3.0"

  on_macos do
  end

  def install
    bin.install "hyperdrive-macos-#{arch}-v#{version}" => "hyperdrive"
  end

  test do
    system "#{bin}/hyperdrive" "--version"
  end
end
